language: generic
sudo: required

services:
 - docker

before_install:
 - docker build -t sumitrusia/docker-react -f Dockerfile.dev .

script:
# - docker run sumitrusia/docker-react npm run test -- --coverage	
 - docker run -e CI=true sumitrusia/docker-react npm run test